spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DB:postgresql}://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:showcase}?createDatabaseIfNotExist=true&?currentSchema=${DB_SCHEMA:repo_dsl}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: true
    locations: classpath:db/migration
