name: Gradle Publish

on:
  push:
    branches:
      - master # Trigger the workflow on pushes to the master branch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Navigate to repository-dsl directory
        run: cd repository-dsl

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        env:
          ACTOR: ${{ github.actor }} # GitHub username
          PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token (automatically provided)
        run: ./gradlew publish
