name: Publish Library to GitHub Packages

on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x repository-dsl/gradlew

      - name: Publish to GitHub Packages
        env:
          ACTOR: ${{ github.actor }}
          PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: repository-dsl//gradlew publish
